name: production CI/CD Github Action

on:
  pull_request:
    branches:
      - main

env:
  BUCKET_NAME: cfst-3457-9a47d50cfec28719547a3c5ece97-prodbucket-i5avv85syj3v

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out job
        uses: actions/checkout@v3

      - name: configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: setup nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: build the code
        run: |
          npm ci
          npm run-script build

      - name: deploy code
        run: aws s3 cp public s3://$BUCKET_NAME/ --recursive
